### ISSUE TITLE
Update to$loginURL needed for GCCH/DOD tenants

### ISSUE THREAD

**Issue by JoeAlanis** [walidelmorsy/Microsoft-365-Compliance-API#1]
Not really an issue, but perhaps a note about the `$loginUrl` variable for users in GCCH/DOD. Along with updating the `$APIResource`, the `$loginURL` needs to be updated to 

`$loginURL = "https://login.microsoftonline.us/"`

[Link to line 40](https://github.com/walidelmorsy/Microsoft-365-Compliance-API/blob/main/Compliace-API.ps1#L40)

**Comment by walidelmorsy** [comment]
Thanks so much Joe! We will update the URL for GCC tenants in the upcoming instruction doc!

**Comment by walidelmorsy** [comment]
Instructions will be updated in the upcoming custom solution release
